# Generated by Django 3.1.3 on 2020-11-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('pokedex_id', models.IntegerField(verbose_name='pokedex id')),
                ('height', models.IntegerField(verbose_name='height')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('health', models.IntegerField(verbose_name='stats')),
                ('attack', models.IntegerField(verbose_name='attack')),
                ('defense', models.IntegerField(verbose_name='defense')),
                ('special_attack', models.IntegerField(verbose_name='special attack')),
                ('special_defense', models.IntegerField(verbose_name='special defense')),
                ('speed', models.IntegerField(verbose_name='speed')),
                ('evolutions', models.ManyToManyField(blank=True, to='pokedex.Pokemon')),
            ],
        ),
    ]
